### ISSUE TITLE
404 for the  /status call for  the targetserver 

### ISSUE THREAD

**Issue by ma198307** [kurtkanaskie/pingstatus-v1-x#1]
Firstly, Thanks for this  onestop solution for api CI-CD. The following targetserver host in TargetServers.json causes  /status  endpoint to return 404 as it executes defaultfaultrule instead of generating custom response message with 200. Eventually maven build fails as  test case  @health @get-status return 500.It's because targetServers.json  contains
"host": "API_NORTHBOUND_DOMAIN"

secondly, I notice out of multiple profiles in  code repo only following two return 200 ok with https  target endpoint all other return 404 or 502 with http or https.
curl -I -X GET 'https://xapi.kurtkanaskie.net/pingstatus-mock/v1/healthcheck'. returns 200
curl -I -X GET 'https://xapi-test.kurtkanaskie.net/pingstatus-mock/v1/healthcheck' return200
I am not sure which  targetserver endpoint/profile  is being used by test suite in dev-1 env, I would assume it uses ngsaas-dev-1  ?
shall user need to use a 3rd party backend api, for this /status endpoint s this is a integration test use case?
 
but from the  maven build I ran , I see the the outbound call in Apigeex probe is going out using http instead of https so its like;
http://${targetServer}/pingstatus-mock/v1/healthcheck

**Comment by kurtkanaskie** [comment]
Thanks for the feedback, I'll take a look and clean this up.

Regarding "API_NORTHBOUND_DOMAIN" that value gets replaced by the value associated with \
"-Dapi.northbound.domain". \
That said, I'm using that as a replacement in TargetServers which implies there needs to be a pingstatus-mock proxy deployed in your org. I guess I should use a common mock like mocktarget.apigee.net or httpbin.org.

I also set a number of variables for the pom.xml profiles in my $HOME/.m2/settings.xml so that may be leaving some blank values. I'll clean this up and also remove some of the profiles, I've also been using this as a test for multiple orgs and envs.

So the all-in-one command could be used with explicit values, or you could update the pom.xml profile:
```
mvn -P test install \
    -Dapigee.org=$ORG \
    -Dapigee.env=$ENV \
    -Dapigee.username=$SA_EMAIL \
    -Dapigee.serviceaccount.file=$SA_KEY_FILE \
    -Dapi.northbound.domain=$ENVGROUP_HOSTNAME
```

You can also set them explicitly in the pom.xml profile and then just run `mvn -P test install`
```
<profile>
	<id>test</id>
	<properties>
		<apigee.profile>test</apigee.profile>
		<apigee.hosturl>https://apigee.googleapis.com</apigee.hosturl>
		<apigee.apiversion>v1</apigee.apiversion>
		<apigee.options>override</apigee.options>
		<apigee.config.dir>target/resources/edge</apigee.config.dir>
		<apigee.config.exportDir>target/test/integration</apigee.config.exportDir>
		<apigee.config.options>update</apigee.config.options>
		<!-- -->
		<!-- Override on command line or replace with your values -->
		<apigee.org>apigeex-mint-kurt</apigee.org>
		<apigee.env>test</apigee.env>
		<apigee.username>cicd-test-service-account@apigeex-mint-kurt.iam.gserviceaccount.com</apigee.username>
		<apigee.serviceaccount.file>/Users/kurtkanaskie/work/APIGEEX/SAs/apigeex-mint-kurt-cicd-test-service-account.json</apigee.serviceaccount.file>
		<api.northbound.domain>xapi-test.kurtkanaskie.net</api.northbound.domain>
	</properties>
</profile>
```

**Comment by kurtkanaskie** [comment]
Fixed by using non-dependent targets.
